version: '3'
services:
  kali-linux-vnc:
    image: kalilinux/kali-rolling
    container_name: kali-linux-vnc
    environment:
      - VNCPWD=password   # Imposta la password del VNC
      - USER=root
    ports:
      - "5901:5901"            # Esponi la porta VNC
    volumes:
      - ./kali-data:/root      # Persistenza dati (facoltativo)
    command: >
      /bin/bash -c "
      apt update &&
      apt install -y tightvncserver xfce4 xfce4-goodies &&
      mkdir -p ~/.vnc &&
      echo '#!/bin/bash' > ~/.vnc/xstartup &&
      echo 'xrdb $HOME/.Xresources' >> ~/.vnc/xstartup &&
      echo 'startxfce4 &' >> ~/.vnc/xstartup &&
      chmod +x ~/.vnc/xstartup &&
      vncserver :1 -geometry 1920x1080 -depth 16 -rfbpasswd password &&
      tail -f /dev/null"
    restart: always


  guacd:
    image: guacamole/guacd
    container_name: backend-guacd
    restart: always

  postgres:
    image: postgres:latest
    container_name: backend-postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
        POSTGRES_DB: guacamole_db             # Nome del database per Guacamole
    volumes:
      - ./db-data:/var/lib/postgresql/data  # Persistenza dei dati di PostgreSQL
    restart: always

  guacamole:
    image: guacamole/guacamole
    container_name: backend-guacamole
    links:
      - postgres:postgres
      - guacd:guacd
    environment:
      - GUACD_HOSTNAME=guacd
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=guacamole_db
      - POSTGRES_USER=postgres    # Deve corrispondere a quello definito nel servizio PostgreSQL
      - POSTGRES_PASSWORD=root
    ports:
      - "8080:8080"                        # Porta per accedere a Guacamole
    restart: always
    depends_on:
      - guacd
      - postgres
